### ISSUE TITLE
docker部署错误

### ISSUE THREAD

**Issue by shuncon** [long2ice/databack#1]
![image](https://user-images.githubusercontent.com/25509201/232650477-9c67fd16-1baa-4903-8cb4-0d9a5858f914.png)

整个配置如介绍内容一直，望指导解决

谢谢大佬

**Comment by shuncon** [comment]
整个配置如介绍内容一致，望指导解决

**Comment by long2ice** [comment]
你好，麻烦把完整的错误贴出来

**Comment by shuncon** [comment]
![image](https://user-images.githubusercontent.com/25509201/232650991-48d890b1-9b0b-4143-b6b1-fd647a084af4.png)

**Comment by shuncon** [comment]
# docker logs -f mysqlbak_databack_1
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/main.py", line 403, in main
    run(
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/databack/databack/app.py", line 18, in <module>
    from databack.api import router
  File "/databack/databack/api/__init__.py", line 3, in <module>
    from databack.depends import set_i18n
  File "/databack/databack/depends.py", line 4, in <module>
    from databack.scheduler import Scheduler
  File "/databack/databack/scheduler.py", line 10, in <module>
    from databack.tasks import run_backup
  File "/databack/databack/tasks.py", line 14, in <module>
    from databack.settings import settings
  File "/databack/databack/settings.py", line 29, in <module>
    sentry_sdk.init(
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/hub.py", line 121, in _init
    client = Client(*args, **kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/client.py", line 143, in __init__
    self._init_impl()
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/client.py", line 211, in _init_impl
    self.transport = make_transport(self.options)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/transport.py", line 534, in make_transport
    return transport_cls(options)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/transport.py", line 142, in __init__
    Transport.__init__(self, options)
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/transport.py", line 56, in __init__
    self.parsed_dsn = Dsn(options["dsn"])
                      ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/utils.py", line 230, in __init__
    raise BadDsn("Unsupported scheme %r" % parts.scheme)
sentry_sdk.utils.BadDsn: Unsupported scheme ''
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1130, in __call__
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/main.py", line 403, in main
    run(
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/databack/databack/app.py", line 18, in <module>
    from databack.api import router
  File "/databack/databack/api/__init__.py", line 3, in <module>
    from databack.depends import set_i18n
  File "/databack/databack/depends.py", line 4, in <module>
    from databack.scheduler import Scheduler
  File "/databack/databack/scheduler.py", line 10, in <module>
    from databack.tasks import run_backup
    sentry_sdk.init(
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/hub.py", line 121, in _init
    client = Client(*args, **kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/client.py", line 143, in __init__
    self._init_impl()
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/client.py", line 211, in _init_impl
    self.transport = make_transport(self.options)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/transport.py", line 534, in make_transport
    return transport_cls(options)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/transport.py", line 142, in __init__
    Transport.__init__(self, options)
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/transport.py", line 56, in __init__
    self.parsed_dsn = Dsn(options["dsn"])
                      ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/utils.py", line 230, in __init__
    raise BadDsn("Unsupported scheme %r" % parts.scheme)
sentry_sdk.utils.BadDsn: Unsupported scheme ''

**Comment by long2ice** [comment]
移除.env中的`SENTRY_DSN`，如果你不打算使用sentry

**Comment by shuncon** [comment]
删除SENTRY_DSN = 'xxx' 项依旧是这样呢
    from databack.api import router
  File "/databack/databack/api/__init__.py", line 3, in <module>
    from databack.settings import settings
  File "/databack/databack/settings.py", line 29, in <module>
    self._init_impl()
  File "/usr/local/lib/python3.11/dist-packages/sentry_sdk/client.py", line 211, in _init_impl
    return transport_cls(options)
           ^^^^^^^^^^^^^^^^^^^^^^
    self.parsed_dsn = Dsn(options["dsn"])
                      ^^^^^^^^^^^^^^^^^^^
sentry_sdk.utils.BadDsn: Unsupported scheme ''

**Comment by shuncon** [comment]
原本我没打算去除，我是按照默认配置先跑一遍的
DB_URL = mysql://root:123456@127.0.0.1:3306/databack
DEBUG = True
REDIS_URL = redis://127.0.0.1:6379/0
SENTRY_DSN = 'xxx'
WORKER = True

**Comment by long2ice** [comment]
你把`.env`和`docker-compose.yml`贴出来看看

**Comment by shuncon** [comment]
# cat docker-compose.yml .env 
version: "3"
services:
  databack:
    restart: always
    env_file: .env
    network_mode: host
    image: ghcr.io/long2ice/databack/databack


DB_URL = mysql://root:123456@127.0.0.1:3306/databack
DEBUG = True
REDIS_URL = redis://127.0.0.1:6379/0
SENTRY_DSN = '119.29.29.29'
WORKER = True

**Comment by shuncon** [comment]
dsn只是一个我自定义修改成其他的来试试也是这样

**Comment by long2ice** [comment]
SENTRY_DSN格式不对，如果你不用就直接删了，README我更新了一下，`ghcr.io/long2ice/databack/databack`换成`ghcr.io/long2ice/databack/databack:full`

**Comment by shuncon** [comment]
我也删除过该项，也是同一个报错

**Comment by long2ice** [comment]
不应该，你删了重新up -d了吗

**Comment by shuncon** [comment]
emm 不过前后端合并的img我先测测

**Comment by shuncon** [comment]
full镜像报错：
注释dsn项得到的错误
  await generate_schema_for_client(connection, safe)
  File "/usr/local/lib/python3.11/dist-packages/tortoise/utils.py", line 31, in generate_schema_for_client
    await generator.generate_from_string(schema)
  File "/usr/local/lib/python3.11/dist-packages/tortoise/backends/base/schema_generator.py", line 448, in generate_from_string
    await self.client.execute_script(creation_string)
  File "/usr/local/lib/python3.11/dist-packages/tortoise/backends/mysql/client.py", line 44, in translate_exceptions_
    return await func(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tortoise/backends/mysql/client.py", line 211, in execute_script
    async with self.acquire_connection() as connection:
  File "/usr/local/lib/python3.11/dist-packages/tortoise/backends/base/client.py", line 326, in __aenter__
    await self.ensure_connection()
  File "/usr/local/lib/python3.11/dist-packages/tortoise/backends/base/client.py", line 322, in ensure_connection
    await self.client.create_connection(with_db=True)
  File "/usr/local/lib/python3.11/dist-packages/tortoise/backends/mysql/client.py", line 130, in create_connection
    raise DBConnectionError(f"Can't connect to MySQL server: {self._template}")
tortoise.exceptions.DBConnectionError: Can't connect to MySQL server: {'host': '127.0.0.1', 'port': 3306, 'user': 'root', 'db': 'databack', 'autocommit': True, 'charset': 'utf8mb4', 'minsize': 1, 'maxsize': 5, 'sql_mode': 'STRICT_TRANS_TABLES'}

ERROR:    Application startup failed. Exiting.

dsn 改回默认的值也是跟之前的报错一样

**Comment by long2ice** [comment]
现在是另外的问题，你数据库连不上，需要自己提供一个数据库

**Comment by shuncon** [comment]
啊这，还以为集成一个mysql了，回头我试试新增一下，现在我要忙的别事情了哈 谢谢大佬

**Comment by shuncon** [comment]
还有个建议就是，如果是需要用户外置一个数据库的话，可以先在项目中配置默认的sqllite，用户后续可以改默认的数据库为mysql就更好了

**Comment by long2ice** [comment]
好的

**Comment by shuncon** [comment]
File "/usr/local/lib/python3.11/dist-packages/tortoise/backends/mysql/client.py", line 130, in create_connection
    raise DBConnectionError(f"Can't connect to MySQL server: {self._template}")
tortoise.exceptions.DBConnectionError: Can't connect to MySQL server: {'host': '192.168.3.2', 'port': 33306, 'user': 'root', 'db': 'databack', 'autocommit': True, 'charset': 'utf8mb4', 'minsize': 1, 'maxsize': 5, 'sql_mode': 'STRICT_TRANS_TABLES'}

ERROR:    Application startup failed. Exiting.
INFO:     Started server process [1]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/tortoise/backends/mysql/client.py", line 114, in create_connection
    self._pool = await mysql.create_pool(password=self.password, **self._template)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncmy/pool.pyx", line 216, in _create_pool
  File "asyncmy/pool.pyx", line 217, in asyncmy.pool._create_pool
  File "asyncmy/pool.pyx", line 145, in fill_free_pool
  File "asyncmy/connection.pyx", line 1299, in _connect
  File "asyncmy/connection.pyx", line 550, in connect
  File "asyncmy/connection.pyx", line 528, in asyncmy.connection.Connection.connect
  File "asyncmy/connection.pyx", line 787, in _request_authentication
  File "asyncmy/connection.pyx", line 600, in read_packet
  File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
  File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
  File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception

**Comment by long2ice** [comment]
检查下MySQL连接信息吧

**Comment by shuncon** [comment]
我解决 了 也要自己搞 emm
