### ISSUE TITLE
请问一下这样是正常的吗

### ISSUE THREAD

**Issue by shuncon** [long2ice/databack#2]
future: <Task finished name='Task-14' coro=<Worker.run() done, defined at /usr/local/lib/python3.11/dist-packages/rearq/worker.py:319> exception=AuthenticationError('Authentication required.')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/rearq/worker.py", line 321, in run
    await self._pre_run()
  File "/usr/local/lib/python3.11/dist-packages/rearq/worker.py", line 308, in _pre_run
    await self._redis.xgroup_create(q, self.group_name, mkstream=True)
  File "/usr/local/lib/python3.11/dist-packages/redis/asyncio/client.py", line 531, in execute_command
2023-04-22 01:19:56.973 | INFO     | databack.scheduler:start:43 - Scheduler will sleep 60 seconds for next task
2023-04-22 01:20:56.975 | INFO     | databack.scheduler:start:43 - Scheduler will sleep 60 seconds for next task

请问一下这样是正常的吗

还有好像不支持redis
REDIS_URL = redis://192.168.111.2:6379:"password"/0

**Comment by long2ice** [comment]
你这 redis url的格式不对，redis://:password@192.168.111.2:6379/0

**Comment by shuncon** [comment]
version: "3"
services:
  databack:
    restart: always
    env_file: .env
    network_mode: host
    image: ghcr.io/long2ice/databack/databack:full
    volumes:
      - /data/shun-mysqlbak/shunbakdata:/databack/shunbakdata
本地/databack/shunbakdata挂载进容器内，并设置存储为本地：
![image](https://user-images.githubusercontent.com/25509201/233766092-4c630c40-83cc-4092-8e51-a624ed7744e9.png)

但是得到错误，emm 有点难受

**Comment by shuncon** [comment]
![image](https://user-images.githubusercontent.com/25509201/233766337-8decf79f-b0aa-47a4-9097-cf88fe0ddbba.png)

**Comment by shuncon** [comment]
![image](https://user-images.githubusercontent.com/25509201/233766427-593a5b8f-760a-4cb2-b1e1-d8e77ecadd4c.png)

**Comment by shuncon** [comment]
哪怕设置为根目录也是错误

**Comment by long2ice** [comment]
贴一下容器日志

**Comment by shuncon** [comment]
023-04-22 06:13:52.276 | INFO     | uvicorn.protocols.http.httptools_impl:send:506 - 192.168.145.1:63726 - "POST /api/storage HTTP/1.1" 500
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databack/databack/api/storage.py", line 67, in create_storage
    await Storage.create(**body.dict())
  File "/usr/local/lib/python3.11/dist-packages/tortoise/models.py", line 1136, in create
    instance = cls(**kwargs)
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tortoise/models.py", line 671, in __init__
    for key in meta.fields.difference(self._set_kwargs(kwargs)):
                                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tortoise/models.py", line 697, in _set_kwargs
    raise ValueError(f"{key} is non nullable field, but null was passed")


scp方式也是同样的错误

**Comment by long2ice** [comment]
修复了，你试试最新的镜像

**Comment by shuncon** [comment]
谢谢 晚点我试试

**Comment by shuncon** [comment]
镜像能不能上传到dockerhub啊 pull好慢啊 ，是不是被dockerhub限制了免费用户了？

**Comment by shuncon** [comment]
![image](https://user-images.githubusercontent.com/25509201/233929216-16f30281-ff2a-439b-88b0-14dfc61a2b39.png)
这个定时任务是不是有坑啊，我设置每天凌晨备份，执行后就自动安排下一次备份的时间为第二天的某点，而不是指定的时间点

**Comment by shuncon** [comment]
![image](https://user-images.githubusercontent.com/25509201/233932018-0afd9001-33ba-4c22-b3f2-4ef0c47e8baa.png)
定时任务是不是有问题啊，每天凌晨4点备份才对，手动执行一次，结果到第二天中午了

**Comment by long2ice** [comment]
更新一下

**Comment by long2ice** [comment]
然后设置环境变量：`TZ=Asia/Shanghai`
